name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Remplacez par la version de .NET souhaitée

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-restore --verbosity normal


    # Étape SonarLint
    - name: SonarLint
      run: dotnet sonarscanner begin /d:sonar.login="YOUR_SONAR_TOKEN"
    
    - name: Build and analyze
      run: dotnet build /t:SonarQube
          
    - name: End SonarLint
      run: dotnet sonarscanner end /d:sonar.login="YOUR_SONAR_TOKEN"
